import '@repo/ui/styles.css';
import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import './globals.css';
import { CartContextProvider, CartUIProvider } from './providers';

const geist = Geist({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'LIgma',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body className={geist.className} data-scroll-behavior="smooth">
        <CartUIProvider>
          <CartContextProvider>{children}</CartContextProvider>
        </CartUIProvider>
      </body>
    </html>
  );
}
